import { useState } from 'react'
import type { TransferItem, TransferStatusUpdate } from '../../types'

interface StitchTransfersPageProps {
  transfers: TransferItem[]
  onUpdateStatus: (id: number, status: TransferStatusUpdate) => Promise<void>
}

export function StitchTransfersPage({
  transfers,
  onUpdateStatus,
}: StitchTransfersPageProps) {
  const [activeFilter, setActiveFilter] = useState<'ACTIVE' | 'PENDING' | 'COMPLETED'>('ACTIVE')
  const [updatingId, setUpdatingId] = useState<number | null>(null)

  const handleAction = async (id: number, status: TransferStatusUpdate) => {
    setUpdatingId(id)
    try {
      await onUpdateStatus(id, status)
    } finally {
      setUpdatingId(null)
    }
  }

  const activeTransfers = transfers.filter((t) => t.status === 'APPROVED' || t.status === 'IN_TRANSIT')
  const pendingTransfers = transfers.filter((t) => t.status === 'PENDING')
  const completedTransfers = transfers.filter((t) => t.status === 'COMPLETED' || t.status === 'REJECTED')

  const filteredTransfers =
    activeFilter === 'ACTIVE'
      ? activeTransfers
      : activeFilter === 'PENDING'
      ? pendingTransfers
      : completedTransfers

  return (
    <div className="p-6 md:p-12 max-w-7xl mx-auto w-full space-y-10 select-none">
      {/* Header */}
      <header className="flex flex-col sm:flex-row sm:items-end justify-between gap-4">
        <div>
          <h2 className="font-serif text-3xl sm:text-4xl font-semibold text-on-surface">
            Transfer Center
          </h2>
          <p className="font-sans text-sm text-on-surface-variant mt-1.5 max-w-2xl">
            Redistribution recommendations generated by PRAVAH&rsquo;s Linear Programming (HiGHS) optimization engine.
          </p>
        </div>

        <div className="flex gap-3">
          <button
            onClick={() => alert('Filtering transfer corridors by state and priority...')}
            className="flex items-center gap-2 border border-primary text-primary px-5 py-2.5 rounded-full font-sans text-xs font-bold uppercase tracking-wider hover:bg-primary/5 transition-colors cursor-pointer"
          >
            <span className="material-symbols-outlined text-[18px]">filter_list</span>
            Filter Corridors
          </button>
        </div>
      </header>

      {/* Intelligence Tabs */}
      <div className="flex gap-8 border-b border-outline-variant/20 text-xs font-sans font-bold uppercase tracking-wider">
        <button
          onClick={() => setActiveFilter('ACTIVE')}
          className={`pb-3 transition-colors cursor-pointer ${
            activeFilter === 'ACTIVE'
              ? 'text-primary border-b-2 border-primary'
              : 'text-on-surface-variant hover:text-on-surface'
          }`}
        >
          Active ({activeTransfers.length})
        </button>
        <button
          onClick={() => setActiveFilter('PENDING')}
          className={`pb-3 transition-colors cursor-pointer ${
            activeFilter === 'PENDING'
              ? 'text-primary border-b-2 border-primary'
              : 'text-on-surface-variant hover:text-on-surface'
          }`}
        >
          Pending Authorization ({pendingTransfers.length})
        </button>
        <button
          onClick={() => setActiveFilter('COMPLETED')}
          className={`pb-3 transition-colors cursor-pointer ${
            activeFilter === 'COMPLETED'
              ? 'text-primary border-b-2 border-primary'
              : 'text-on-surface-variant hover:text-on-surface'
          }`}
        >
          Completed / Resolved ({completedTransfers.length})
        </button>
      </div>

      {/* Transfer List */}
      <div className="bg-white rounded-2xl border border-outline-variant/15 overflow-hidden">
        {/* Table Header */}
        <div className="grid grid-cols-12 gap-4 px-6 py-4 border-b border-outline-variant/15 font-sans text-[11px] font-bold text-on-surface-variant uppercase tracking-wider bg-surface-container-low">
          <div className="col-span-12 md:col-span-3">Unit / ID</div>
          <div className="col-span-12 md:col-span-4">Corridor &amp; Route</div>
          <div className="col-span-12 md:col-span-3">Status &amp; Progress</div>
          <div className="col-span-12 md:col-span-2 text-right">Actions</div>
        </div>

        {/* Transfer Rows */}
        <div className="divide-y divide-outline-variant/10 font-sans text-xs">
          {filteredTransfers.length > 0 ? (
            filteredTransfers.map((t) => {
              const isApproved = t.status === 'APPROVED' || t.status === 'IN_TRANSIT'

              return (
                <div
                  key={t.id}
                  className="grid grid-cols-12 gap-4 items-center px-6 py-5 hover:bg-f5f1ee transition-colors"
                >
                  {/* Unit / ID */}
                  <div className="col-span-12 md:col-span-3 flex items-center gap-3">
                    <div className="w-10 h-10 rounded-full bg-primary/10 flex items-center justify-center text-primary shrink-0">
                      <span className="material-symbols-outlined text-[20px]">bloodtype</span>
                    </div>
                    <div>
                      <div className="font-bold text-sm text-on-surface">
                        {t.blood_group} {t.component}
                      </div>
                      <div className="text-[11px] text-on-surface-variant">
                        TRX-0{t.id} · {t.quantity} Units
                      </div>
                    </div>
                  </div>

                  {/* Route */}
                  <div className="col-span-12 md:col-span-4">
                    <div className="flex items-center gap-2 text-on-surface font-semibold">
                      <span>{t.source_bank.replace('[DEMO] ', '')}</span>
                      <span className="material-symbols-outlined text-[16px] text-on-surface-variant">arrow_forward</span>
                      <span className="text-primary">{t.destination_bank.replace('[DEMO] ', '')}</span>
                    </div>
                    <div className="text-[11px] text-on-surface-variant mt-0.5 font-medium">
                      {t.route || 'Dedicated Cold Van (22°C)'}
                    </div>
                  </div>

                  {/* Multi-stage Progress Stepper */}
                  <div className="col-span-12 md:col-span-3">
                    <div className="flex justify-between mb-1.5 text-[10px] font-bold uppercase tracking-wider text-on-surface-variant">
                      <span className="text-secondary">Rec</span>
                      <span className={isApproved ? 'text-secondary font-bold' : 'text-primary'}>App</span>
                      <span className={isApproved ? 'text-secondary' : 'opacity-40'}>Prep</span>
                      <span className={isApproved ? 'text-primary font-bold' : 'opacity-40'}>Transit</span>
                      <span className="opacity-40">Del</span>
                    </div>
                    <div className="w-full h-1.5 bg-outline-variant/30 rounded-full overflow-hidden">
                      <div
                        className="h-full bg-primary rounded-full transition-all duration-500"
                        style={{ width: isApproved ? '75%' : '30%' }}
                      />
                    </div>
                  </div>

                  {/* Actions / Status */}
                  <div className="col-span-12 md:col-span-2 flex justify-end gap-2">
                    {t.status === 'PENDING' ? (
                      <>
                        <button
                          disabled={updatingId === t.id}
                          onClick={() => handleAction(t.id, 'APPROVED')}
                          className="px-3.5 py-1.5 bg-secondary text-white rounded-lg text-xs font-bold uppercase tracking-wider hover:opacity-90 transition-opacity cursor-pointer disabled:opacity-50"
                        >
                          Approve
                        </button>
                        <button
                          disabled={updatingId === t.id}
                          onClick={() => handleAction(t.id, 'REJECTED')}
                          className="px-2.5 py-1.5 border border-outline-variant text-on-surface-variant rounded-lg text-xs font-semibold hover:text-primary transition-colors cursor-pointer disabled:opacity-50"
                        >
                          Reject
                        </button>
                      </>
                    ) : (
                      <span
                        className={`px-3 py-1 rounded-full text-[10px] font-bold uppercase tracking-wider ${
                          isApproved
                            ? 'bg-secondary-container text-secondary'
                            : 'bg-surface-variant text-on-surface-variant'
                        }`}
                      >
                        {t.status}
                      </span>
                    )}
                  </div>
                </div>
              )
            })
          ) : (
            <div className="p-8 text-center text-on-surface-variant">
              No transfers in this category.
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
