import { useState, useEffect } from 'react'
import type { TransferItem } from '../../types'

interface Step8TransfersProps {
  transfers: TransferItem[]
  selectedTransferId: number | null
  onSelectTransfer: (id: number) => void
  onNavigateToStep: (step: string, filter?: Record<string, string>) => void
}

export function Step8Transfers({
  transfers,
  selectedTransferId,
  onSelectTransfer,
  onNavigateToStep,
}: Step8TransfersProps) {
  const pendingTransfers = transfers.filter((t) => t.status === 'PENDING')
  const initialSelected = transfers.find((t) => t.id === selectedTransferId) || pendingTransfers[0] || transfers[0]
  const [activeTransfer, setActiveTransfer] = useState<TransferItem | null>(initialSelected || null)

  useEffect(() => {
    if (!activeTransfer && transfers.length > 0) {
      setActiveTransfer(transfers[0])
    }
  }, [transfers, activeTransfer])

  return (
    <div className="p-6 md:p-12 max-w-7xl mx-auto w-full space-y-10 select-none font-sans">
      {/* Header */}
      <header className="flex flex-col sm:flex-row sm:items-end justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <span className="px-2.5 py-0.5 bg-primary/10 text-primary text-[10px] font-bold rounded-full uppercase tracking-wider">
              Step 08 of 10
            </span>
            <span className="text-xs text-on-surface-variant font-bold uppercase tracking-wider">
              Transfer Recommendations
            </span>
          </div>
          <h2 className="font-serif text-3xl sm:text-4xl font-semibold text-on-surface tracking-tight mt-1">
            What does PRAVAH recommend?
          </h2>
          <p className="text-xs sm:text-sm text-on-surface-variant mt-1 max-w-2xl">
            Optimized redistribution dispatches generated by linear programming and awaiting human authorization.
          </p>
        </div>

        <button
          onClick={() => {
            if (activeTransfer) {
              onSelectTransfer(activeTransfer.id)
            }
            onNavigateToStep('approval')
          }}
          className="bg-primary text-white px-7 py-3 rounded-full text-xs font-bold uppercase tracking-wider hover:bg-primary-container transition-colors cursor-pointer shadow-md flex items-center gap-2 self-start sm:self-auto shrink-0"
        >
          <span>Review &amp; Authorize</span>
          <span className="material-symbols-outlined text-[18px]">arrow_forward</span>
        </button>
      </header>

      {/* Main Grid: Transfer List (Left 60%) + Transfer Reason & Logistics (Right 40%) */}
      <div className="flex flex-col lg:flex-row gap-6">
        {/* Transfer Recommendations List */}
        <div className="w-full lg:w-3/5 space-y-3">
          <div className="flex justify-between items-center hairline-b pb-2">
            <h3 className="font-serif text-xl font-semibold text-on-surface">
              Pending Recommendations ({pendingTransfers.length})
            </h3>
            <span className="text-xs text-on-surface-variant">Select to review</span>
          </div>

          {transfers.length === 0 ? (
            <div className="p-8 text-center text-xs text-on-surface-variant bg-white rounded-xl">
              No transfer recommendations found.
            </div>
          ) : (
            <div className="space-y-3">
              {transfers.slice(0, 7).map((t) => {
                const isSelected = activeTransfer?.id === t.id

                return (
                  <div
                    key={t.id}
                    onClick={() => {
                      setActiveTransfer(t)
                      onSelectTransfer(t.id)
                    }}
                    className={`p-5 rounded-2xl border transition-all cursor-pointer flex justify-between items-center ${
                      isSelected
                        ? 'bg-f5f1ee border-primary ring-1 ring-primary/20 shadow-xs'
                        : 'bg-white border-outline-variant/15 hover:bg-f5f1ee/40'
                    }`}
                  >
                    <div className="space-y-1">
                      <span className="text-[10px] font-bold uppercase text-primary">
                        Transfer #{t.id}
                      </span>
                      <div className="flex items-center gap-2 text-sm font-bold text-on-surface">
                        <span className="max-w-[160px] truncate">{t.source_bank}</span>
                        <span className="material-symbols-outlined text-[16px] text-on-surface-variant">arrow_forward</span>
                        <span className="text-primary max-w-[160px] truncate">{t.destination_bank}</span>
                      </div>
                      <p className="text-xs text-on-surface-variant">
                        {t.blood_group} {t.component} · {t.quantity} Units
                      </p>
                    </div>

                    <span
                      className={`px-3 py-1 rounded-full text-[10px] font-bold uppercase ${
                        t.status === 'APPROVED'
                          ? 'bg-secondary-container text-secondary'
                          : t.status === 'PENDING'
                          ? 'bg-primary/10 text-primary'
                          : 'bg-surface-variant text-on-surface-variant'
                      }`}
                    >
                      {t.status}
                    </span>
                  </div>
                )
              })}
            </div>
          )}
        </div>

        {/* Selected Recommendation Detail & Justification */}
        <div className="w-full lg:w-2/5 bg-f5f1ee p-8 rounded-2xl border border-outline-variant/15 flex flex-col justify-between space-y-6">
          {activeTransfer ? (
            <div className="space-y-4">
              <span className="text-[10px] font-bold text-on-surface-variant uppercase tracking-widest block">
                Transfer Details · #{activeTransfer.id}
              </span>
              <h3 className="font-serif text-2xl font-semibold text-on-surface">
                {activeTransfer.quantity} Units {activeTransfer.blood_group} {activeTransfer.component}
              </h3>

              <div className="p-4 bg-white rounded-xl border border-outline-variant/15 space-y-2.5 text-xs">
                <div className="flex justify-between">
                  <span className="text-on-surface-variant font-semibold">Source Hub:</span>
                  <span className="font-bold text-on-surface max-w-[200px] truncate">{activeTransfer.source_bank}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-on-surface-variant font-semibold">Recipient Bank:</span>
                  <span className="font-bold text-primary max-w-[200px] truncate">{activeTransfer.destination_bank}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-on-surface-variant font-semibold">Corridor:</span>
                  <span className="text-on-surface max-w-[200px] truncate">{activeTransfer.route || 'Refrigerated Cold Corridor'}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-on-surface-variant font-semibold">Vehicle:</span>
                  <span className="text-on-surface">{activeTransfer.vehicle || 'Refrigerated Van (22°C)'}</span>
                </div>
              </div>

              {/* Why This Transfer Section */}
              <div className="space-y-2 text-xs">
                <span className="font-bold text-on-surface uppercase text-[11px] block">
                  Why this transfer recommendation?
                </span>
                <ul className="space-y-2 text-on-surface-variant">
                  <li className="flex items-start gap-2">
                    <span className="material-symbols-outlined text-secondary text-[16px] shrink-0 mt-0.5">check</span>
                    <span><strong>Shortage at destination:</strong> Deficit identified by demand forecasting model.</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="material-symbols-outlined text-secondary text-[16px] shrink-0 mt-0.5">check</span>
                    <span><strong>Surplus at source:</strong> Units identified for redistribution to prevent expiration.</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="material-symbols-outlined text-secondary text-[16px] shrink-0 mt-0.5">check</span>
                    <span><strong>Cold-chain feasible:</strong> Compliant transit window within temperature threshold.</span>
                  </li>
                </ul>
              </div>
            </div>
          ) : (
            <div className="text-center py-12 text-on-surface-variant text-xs">
              Select a transfer recommendation to review parameters.
            </div>
          )}

          <div className="space-y-3 pt-4 border-t border-outline-variant/20">
            <button
              onClick={() => {
                if (activeTransfer) {
                  onSelectTransfer(activeTransfer.id)
                }
                onNavigateToStep('approval')
              }}
              className="w-full py-3.5 bg-primary text-white text-xs font-bold uppercase rounded-full hover:bg-primary-container transition-colors cursor-pointer shadow-xs flex items-center justify-center gap-2"
            >
              <span>Step 09 · Authorize Transfer</span>
              <span className="material-symbols-outlined text-[16px]">arrow_forward</span>
            </button>

            <div className="flex justify-between items-center text-xs text-on-surface-variant">
              <button
                onClick={() => onNavigateToStep('optimize')}
                className="hover:text-primary transition-colors cursor-pointer"
              >
                ← Step 07 Optimize
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
